### ISSUE TITLE
bosto kingtee 22U mini

### ISSUE THREAD

**Issue by antonvdh** [aidyw/bosto-2g-linux-kernel-module#1]
Can you make it work for the bosto kingtee 22U mini.
Need a digitizertablet calibration for Ubuntu 14.04.

**Comment by aidyw** [comment]
I assume its not working. I have no idea what chipset that is.
Aidan

**Comment by antonvdh** [comment]
Where can I find which chipset is onboard.

2015-08-28 10:57 GMT+02:00 Aidan Walton notifications@github.com:

> I assume its not working. I have no idea what chipset that is.
> Aidan

**Comment by antonvdh** [comment]
The tablet works right out of the box but the stylus is dead.

**Comment by aidyw** [comment]
If the vendor and product part of the USB info are different to that which
is hard coded into the driver.( If I remember the 22 HD is 0x0b57 0x0916.},
then the driver will not recognize the stylus. This does not identify the
chipset sprcifically, but if you don't have a match here then you can be
sure the driver wont even try to attach to the device.

**Comment by antonvdh** [comment]
lsusb shows this:
Bus 005 Device 002: ID 0ed1:7821 WinMaxGroup

2015-09-01 10:18 GMT+02:00 Aidan Walton notifications@github.com:

> If the vendor and product part of the USB info are different to that which
> is hard coded into the driver.( If I remember the 22 HD is 0x0b57 0x0916.},
> then the driver will not recognize the stylus. This does not identify the
> chipset sprcifically, but if you don't have a match here then you can be
> sure the driver wont even try to attach to the device.
>

**Comment by aidyw** [comment]
Anton,

0x0b57 is Hanwang corporation. AFAIK they are the hardware vendor that Bosto used in the 22HD and HD+ and also the 14WA. Bosto are only integrating this hardware into a tablet. Hanwang developed the touch sensor and associated chipsets. This is an assumtion as I never opened the case to look at the chips. Anyway. What you just posted shows a totally different Vendor -ID 0x0ED1. As you say WinMax. 

Are you sure this is the correct device? It looks to me like a USB Flash drive not a tablet.

**Comment by antonvdh** [comment]
Yes I am sure because when I unplug the digitzer tablet I don't  this line
Bus 005 Device 002: ID 0ed1:7821 WinMaxGroup

anton@MSI-CR610:~/bosto-2g-linux-kernel-module$ lsusb
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 005 Device 002: ID 0ed1:7821 WinMaxGroup 
Bus 005 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 002: ID 046d:c00e Logitech, Inc. M-BJ58/M-BJ69 Optical Wheel Mouse

anton@MSI-CR610:~$ lsmod | grep bosto_2g
bosto_2g               13477  0 

anton@MSI-CR610:~$ sudo echo -n 'file .//bosto_2g.ko line 230 +p' > /control
bash: /control: Permission denied

I see the cursor moving when I move the stylus but its not calibrated and I cannot draw any lines with it.

**Comment by antonvdh** [comment]
Yes got it worked I just needed to disable the notebook display so only the digitizer display is on.
But sometimes I see some horizontal lines appearing for a second. 
That is not good for the digitizer tablet I think. Can you fix this.
So I have to stay with windows 7 for now.
But it works.
PS MyPaint 1.1.0 did not work but the Gimp 2.8 works perfect.
![20150901_223030](https://cloud.githubusercontent.com/assets/1901385/9615692/240397b4-50fa-11e5-933e-44f5a7a5a5f9.jpg)

**Comment by aidyw** [comment]
Glad to hear this. Actually you inspired me to resolve a problem with lines
being drawn to the origin. I made some simple changes to the master branch
which has improved the initial response of the stylus and got around lines
drawn to the origin when the stylus button is pressed and the pen is in
contact. Nothing to do with your situation for sure, still.....  please
don’t resort to Windows...... keep trying.
Aidan

**Comment by antonvdh** [comment]
Thanks.
I really want to stay with ubuntu. But with these strange flickering lines
I am afraid the digitizer is going to be defect.
What do you suggest.
Op 2 sep. 2015 15:11 schreef "Aidan Walton" notifications@github.com:

> Glad to hear this. Actually you inspired me to resolve a problem with lines
> being drawn to the origin. I made some simple changes to the master branch
> which has improved the initial response of the stylus and got around lines
> drawn to the origin when the stylus button is pressed and the pen is in
> contact. Nothing to do with your situation for sure, still..... please
> don’t resort to Windows...... keep trying.
> Aidan
>

**Comment by aidyw** [comment]
Sorry, i dont have any

**Comment by antonvdh** [comment]
Ok how can I change the stylus button binding.
Op 2 sep. 2015 17:53 schreef "Aidan Walton" notifications@github.com:

> Sorry, i dont have any

**Comment by aidyw** [comment]
I think either under x windows or directly in krita. Never needed to do it.
So i dont know. I think Leslie did this for some reason. But i don't know
for sure its possible

**Comment by aidyw** [comment]
If you read the readme.md something Leslie wrote there makes reference to
this kind of manipulation

**Comment by aidyw** [comment]
I have to day Anton, im at a loss to understand how its working at all,
unless you changed the usb details in the code. Otherwise the bosto_2g
driver should not bind to it. Are you sure which driver is dealing with it?
Perhaps its the wacom built in driver in ubuntu.
Aidan

**Comment by antonvdh** [comment]
Would be nice if I could change within ubuntu upper bottom is for example
ctrl+middle mouse button and lower button is set to left mouse click. Thats
all.
In the software for example blender I can then make bindings.

I will also try another workstation with nvidia gtx gpu to see if I still
have flickering lines when moving the stylus.  I have now tested with ati
gpu.
Op 2 sep. 2015 18:05 schreef "Aidan Walton" notifications@github.com:

> I think either under x windows or directly in krita. Never needed to do it.
> So i dont know. I think Leslie did this for some reason. But i don't know
> for sure its possible

**Comment by lesliev** [comment]
Correct, I suggest changing the key bindings in whatever programs you are using. You can do simple key translation in Linux but you can't do key combinations (as far as I've been able to determine). The benefit of using the key binding editor of whatever program you use is that you can set up the keys similarly in many different programs so that you don't have to re-learn when you switch programs.

**Comment by antonvdh** [comment]
In that case we need to know the default stylus button settings within
Ubuntu.
I can only see that when using windows.
Op 2 sep. 2015 23:45 schreef "Leslie Viljoen" notifications@github.com:

**Comment by antonvdh** [comment]
Keep getting flickering lines maybe its the ATI Ubuntu driver anyhow cannot work with it this way.
Howto uninstall the driver ?

**Comment by antonvdh** [comment]
Tested on my Nvidia system .
No flickering lines tablet works now awesome.

**Comment by aidyw** [comment]
Great. I won't mention my issues with Nvidia then. Glad you are happy.

**Comment by antonvdh** [comment]
I also got your driver work with opensuse 13.2.
But as with Ubuntu the pointer is very far away from the pencil when using a second screen. Please make a calibration option.
![20151022_120327](https://cloud.githubusercontent.com/assets/1901385/10662620/39bdc384-78b6-11e5-8109-886159743785.jpg)

**Comment by lesliev** [comment]
Please read my notes here: https://github.com/lesliev/bosto_14wa#multiple-screens
You can use "xinput --map-to-output" or download my inputtransform script there which gives you a menu to choose screens which can be a bit faster. You'll need to install Ruby to use the script.

**Comment by antonvdh** [comment]
Can I also set the pointer to left handed?

**Comment by antonvdh** [comment]
Tell me how it works:
This program constrains a pointer to a screen. Use --reset to undo this.
Press ctrl-c at any time to cancel.

Please select the stylus device:
  [1] Virtual core XTEST pointer
  [2] Logitech USB-PS/2 Optical Mouse
  [3] UNIPEN TABLET
3

Please select the tablet monitor:
HDMI-0

Please enter a number in the range 1..0 or press ctrl-c to exit
1

Please enter a number in the range 1..0 or press ctrl-c to exit

**Comment by aidyw** [comment]
This calibration can be done via a script. Its part of x11. I have a
website somewhere, but each setup will be different. And orientation of the
screens is unknown so this is not what i would consider a driver issue. You
could argue otherwise but its a lot of trouble to integrate. I just run a
small script to do this.
Aidan

**Comment by lesliev** [comment]
@antonvdh that's a bug in my script. Use xinput without the script instead:
xinput --map-to-output 'UNIPEN TABLET' 'HDMI-0'

Can you also run 'xrandr' and post the output so that I can fix the script?
Thanks!

@aidyw how does this completely different tablet work with our Bosto driver??

**Comment by antonvdh** [comment]
Thanks I will do that as soon as I restored my linux partition because windows 10 has ruined it
when upgrading win 7. how stupid can I be  lol

**Comment by antonvdh** [comment]
Did xinput --map-to-output 'UNIPEN TABLET' 'HDMI-0' but it did not work. pointer is still to far away from the pencil.

linux-nfs:/home/anton/Downloads/bosto_14wa-master/scripts # xrandr
Screen 0: minimum 8 x 8, current 3520 x 1200, maximum 16384 x 16384
DVI-I-0 disconnected (normal left inverted right x axis y axis)
DVI-I-1 disconnected (normal left inverted right x axis y axis)
DVI-I-2 connected 1600x1200+1920+0 (normal left inverted right x axis y axis) 432mm x 324mm
   1600x1200     60.00_+
   1280x1024     75.02    60.02  
   1280x960      60.00  
   1152x864      75.00  
   1024x768      75.03    70.07    60.00  
   800x600       75.00    72.19    60.32    56.25  
   640x480       75.00    72.81    59.94  
HDMI-0 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 0mm x 0mm
   1920x1080     60.00_\+  59.94    50.00    60.00    50.04  
   1680x1050     59.95  
   1440x900      59.89  
   1360x768      60.02  
   1280x1024     75.02    60.02  
   1280x960      60.00  
   1280x800      74.93    59.81  
   1280x720      60.00    59.94    50.00  
   1024x768      75.03    70.07    60.00  
   800x600       75.00    72.19    60.32  
   720x576       50.00    50.08  
   720x480       59.94    60.05  
   640x480       75.00    72.81    59.94    59.93  
DVI-I-3 disconnected (normal left inverted right x axis y axis)

**Comment by lesliev** [comment]
Is HDMI-0 the tablet monitor? I'm surprised it has so many resolution options.

**Comment by antonvdh** [comment]
Yes HDMI=0 is the tablet monitor.
Op 26 okt. 2015 22:30 schreef "Leslie Viljoen" notifications@github.com:

**Comment by lesliev** [comment]
@antonvdh I made the script work with your display names: https://github.com/lesliev/bosto_14wa/blob/master/scripts/inputtransform

...but as far as I know, "xinput --map-to-output" does the same calculation I am doing. It multiplies the x and y co-ordinates by a matrix so that the cursor is scaled to fit the display you want. 

When you say "the pointer is too far away from the pencil", what exactly do you mean? On mine, before I run xinput or inputtransform, if I move the pen a little, the cursor moves a lot. If the monitors are configured to be side-by-side, one tablet-width of pen movement moves from the left of the left-most monitor all the way over to the right of the right-most monitor. But if I go all the way to the top left corner of the tablet, the cursor comes closer to the pen.

Is that what's happening for you?

**Comment by antonvdh** [comment]
![pointer](https://cloud.githubusercontent.com/assets/1901385/10749916/19d540e8-7c70-11e5-8f49-e882df48fcb4.png)
In my case the pencil and pointer distance looked like you see on the picture when enabling multi-monitor. In any direction when moving the pencil.

Anyhow the new script works awesome many thanks.
I have only one question left.
The shortcuts for the buttons on the pencil ?
How to change them or can you tell me what the default shortcuts are.
I need the right mouse button for the pencil.

**Comment by lesliev** [comment]
Interesting.

The button on the pen should send a right-click. There are two sections like this in the code for the driver, which detect the stylus button and report "BTN_STYLUS2" to the system, which is usually interpreted as a right-click. If you'd like that to be a middle-click, change it to BTN_STYLUS in both sections. 

```
            switch (data[1]) {
                case 0xe0 ... 0xe1:
                    input_report_key(input_dev, BTN_STYLUS2, 0);
                    break;
                case 0xe2 ... 0xe3:
                    input_report_key(input_dev, BTN_STYLUS2, 1);
                    break;
            }
```

Alternatively, if clicking the stylus button does nothing, the 0xe0..0xe1 numbers are wrong. In that case you'd need to activate the debug messages and figure out what your tablet sends when the stylus button is pressed. Read "diagnostics" to see how to do that: https://github.com/aidyw/bosto-2g-linux-kernel-module#diagnostics

I'm still not sure what tablet you have and why it works at all with this driver!

**Comment by antonvdh** [comment]
For me the button has two options up and down.
Up acts as left mouse click and down should be right click but is not working.
I have no idea what the down side button shortcut is.
I will read the diagnostics but its complicating.

**Comment by lesliev** [comment]
Add something like this:
`dev_dbg(&dev->dev, "BUTTON: ID:Tool %x\n", data[1]);`

Above each `switch (data[1]) {` which checks for a click.

Then compile and install the driver again.

Unplug and plug in the tablet again, then turn on diagnostics for "BUTTON" (instead of PEN_IN) as detailed here:
https://github.com/lesliev/bosto_14wa#diagnostics

You can then run this to watch the log file: 
sudo tail -f /var/log/syslog

Press the button that's not doing anything and see what numbers get dumped in the log.

**Comment by aidyw** [comment]
Hey guys, 
I have only been following this discussion via e-mail but having logged into Git I see a few other things. In the background I was thinking a bit about how to get the multi-screen scaling sorted. However I have noticed something that I didn't initially realize. After running xrandr we see that the Bosto Tablet replies and its EDID data gives lots of useful info regarding resolutions etc. 

Big problem though. Certainly on my hardware the Bosto guys have not fully programmed the EDID data. The Identifier, ModelName and VendorName are all set as generic: HDMI,HDMI,CVT.

Now what use this is could be anyone's guess. But in contrast my second monitor replies with "HZ281H,HZ281H,HSD". From this we can identify correctly that this particular video port is connected to my Hanns.G monitor.

What am I supposed to do with the Bosto, port, as it just says. HDMI. NOT useful.

Any attempt at writing a script to automatically work out if the Bosto is left or right, becomes nigh on impossible. The best we can do is assume the other vendors are correctly identifying themselves and then whatever is left must be the Bosto. That's plain horrible.

This is sloppy on the part of Bosto. Is this just my version of the hardware?

I don't want to go further trying to identify and trigger scripts to sort out X inputs correctly if this data is so nasty. Bosto. Boooo.

**Comment by aidyw** [comment]
BTW,
This page is very helpful to understand the transformation matrix settings that I am using to get my dual screen setups scripts working:

http://ubuntuforums.org/showthread.php?t=1656089

**Comment by aidyw** [comment]
Nice work BTW Leslie,

Your script makes a neat job of this. So much less painful than I had before. Still my comments still stand, without correct and useful EDID data, your approach 'the human touch' seems the only reliable solution.

Thanks, that's a very nice wrapper around what I was already doing. But now it's much easier. :)

**Comment by lesliev** [comment]
Yeah, it is a bit painful. It would be nice to somehow integrate with the "displays" program (assuming you are on Gnome) - that shows which monitor is which with a little pop-up. Even if there was a something that popped up a similar display of rectangles indicating monitors, you pick one and it constrains to that - nice. But I find the script fairly convenient.

Interesting that the script seems to work when --map-to-output doesn't - you'd think that xinput could properly calculate the matrix.

**Comment by antonvdh** [comment]
How can I save the script settings for multiple screens.
I cannot get the right-click button working.

**Comment by lesliev** [comment]
Take the hashes out at the beginning of these two lines:
https://github.com/lesliev/bosto_14wa/blob/master/scripts/inputtransform#L206

Then you'll see the xinput command the script is running.

How far did you get, trying to figure out what the tablet sends when you do a right-click?

**Comment by antonvdh** [comment]
When I restart the computer lsmod | grep bosto_2g is not showing anything.
Because openSUSE update the kernelits is ot necessary to install the bosto_g2 driver , It just works. But for testing I still do.
For multiple monitor I still use script /inputransform works awesome.

Running the following command:
xinput set-prop 'UNIPEN TABLET' 'Coordinate Transformation Matrix' 0.5454545454545454 0 0.45454545454545453 0 0.9 0.0 0 0 1

I have no idea where to change the  "BTN_STYLUS2" settings.

sudo tail -f /var/log/syslog is not working for opensuse, I could do dmesg. 
The only problem is the right-click is not working.

P.s Mypaint 1.1.0 is not working with the driver.
Inkscape, Gimp, Krita and Blender work fine.
But for blender I need the right-click button otherwise its useless for me.

**Comment by antonvdh** [comment]
I see now the below button is also not assigned under windows 10.
Which driver file should I change to set the shortcut key below button.

**Comment by lesliev** [comment]
This makes me think you are not using the bosto_2g driver at all:
`When I restart the computer lsmod | grep bosto_2g is not showing anything.
Because openSUSE update the kernelits is ot necessary to install the bosto_g2 driver , It just works. But for testing I still do.`

bosto_2g is definitely not in the kernel.

These are the lines I was pointing you to, in the file bosto_2g.c:
https://github.com/aidyw/bosto-2g-linux-kernel-module/blob/master/bosto_2g.c#L233
https://github.com/aidyw/bosto-2g-linux-kernel-module/blob/master/bosto_2g.c#L236
https://github.com/aidyw/bosto-2g-linux-kernel-module/blob/master/bosto_2g.c#L279
https://github.com/aidyw/bosto-2g-linux-kernel-module/blob/master/bosto_2g.c#L282

Add something like this above each 'case' statement:
`dev_dbg(&dev->dev, "BUTTON: ID:Tool %x\n", data[1]);`

Then compile and install the driver again.

Unplug and plug in the tablet again, then turn on diagnostics for "BUTTON" (instead of PEN_IN) as detailed here:
https://github.com/lesliev/bosto_14wa#diagnostics

You can then run this to watch the log file: 
sudo tail -f /var/log/syslog
(if this doesn't work on Suse, google 'how view syslog suse')

Press the button that's not doing anything and see what numbers get dumped in the log.

Of course, if you are not really using bosto_2g, none of this will work.

**Comment by antonvdh** [comment]
I am using the driver :
linux-nfs:/home/anton/bosto-2g-linux-kernel-module-master # lsmod | grep bosto_2g
bosto_2g               13650  0 

syslog is not used anymore.
I have no idea how to use rsyslog.

**Comment by lesliev** [comment]
Is there not a /var/log/messages you can tail?
Try: `sudo tail -f /var/log/messages`

Otherwise, what files are in /var/log?

**Comment by antonvdh** [comment]
sorry for the delay.

I added these lines as you described in bosto_2g.c and reinstalled the driver
Add something like this above each 'case' statement:
dev_dbg(&dev->dev, "BUTTON: ID:Tool %x\n", data[1]); 

Started turn_on_debug

linux-nfs:/home/anton # tail -f /var/log/messages
2015-11-03T11:30:02.020367+01:00 linux-nfs CRON[5571]: pam_unix(crond:session): session closed for user root
2015-11-03T11:30:02.049444+01:00 linux-nfs systemd: pam_unix(systemd-user:session): session closed for user root
2015-11-03T11:45:01.029568+01:00 linux-nfs cron[5668]: pam_unix(crond:session): session opened for user root by (uid=0)
2015-11-03T11:45:01.031203+01:00 linux-nfs cron[5669]: pam_unix(crond:session): session opened for user root by (uid=0)
2015-11-03T11:45:01.038803+01:00 linux-nfs systemd: pam_unix(systemd-user:session): session opened for user root by (uid=0)
2015-11-03T11:45:01.074629+01:00 linux-nfs CRON[5669]: pam_unix(crond:session): session closed for user root
2015-11-03T11:45:01.118436+01:00 linux-nfs CRON[5668]: pam_unix(crond:session): session closed for user root
2015-11-03T11:45:01.141555+01:00 linux-nfs systemd: pam_unix(systemd-user:session): session closed for user root
2015-11-03T11:52:36.337664+01:00 linux-nfs su: (to root) anton on pts/4
2015-11-03T11:52:36.338527+01:00 linux-nfs su: pam_unix(su:session): session opened for user root by anton(uid=1000)

clicking the below button nothing happens.

**Comment by antonvdh** [comment]
maybe it is easier for me to change the upper button to right-mouse click shortcut.
Which BTN_TOUCH should I change into BTN_STYLUS2?

**Comment by antonvdh** [comment]
I do not succeed to set the button to right or left mouse click shortcut, for me it always stays middle mouse click shortcut.

The larger Bosto stylus has a button that can rock to two positions but unfortunately both positions send the same signal back to the computer so it can't be used to perform both right and middle-click.

With windows 7 ,8 or 10 we can set both positions but i want to stay faithful to Linux openSuse.

**Comment by lesliev** [comment]
turn_on_debug does things like this:
`echo -n 'format "TOOL" +p' > /sys/kernel/debug/dynamic_debug/control`

Since your extra dbg statement uses BUTTON, you need to do 
`echo -n 'format "BUTTON" +p' > /sys/kernel/debug/dynamic_debug/control`

"With windows 7 ,8 or 10 we can set both positions" - are you saying the button on the front of the pen does two different things in Windows?

**Comment by antonvdh** [comment]
"With windows 7 ,8 or 10 we can set both positions" - are you saying the button on the front of the pen does two different things in Windows?

Yes I can set it to two different shortcuts.
For example up button  left mouse click down button right mouse click.

**Comment by lesliev** [comment]
Oh. But earlier you said: "The larger Bosto stylus has a button that can rock to two positions but unfortunately both positions send the same signal back to the computer so it can't be used to perform both right and middle-click."

So this seems to be a difference in the two styli. I have a small and a large but I thought the small one's button only had a single click, not a rocker. I'll take a look later.

Could you possibly post images of each stylus?

**Comment by antonvdh** [comment]
I only have te large 22U stylus and commented on this see stylus button https://github.com/lesliev/bosto_14wa/blob/master/README.md

**Comment by antonvdh** [comment]
Pencil 22U mini;
![pencil22umini](https://cloud.githubusercontent.com/assets/1901385/10932735/92413afa-82d3-11e5-940a-74b45dc751f1.jpg)

**Comment by antonvdh** [comment]
linux-nfs:/home/anton/bosto_14wa-master/scripts # sudo tail -f /var/log/messages
2015-11-04T09:00:01.088271+01:00 linux-nfs cron[2671]: pam_unix(crond:session): session opened for user root by (uid=0)
2015-11-04T09:00:01.089059+01:00 linux-nfs cron[2672]: pam_unix(crond:session): session opened for user root by (uid=0)
2015-11-04T09:00:01.092963+01:00 linux-nfs systemd[1]: Cannot add dependency job for unit cups.socket, ignoring: Unit cups.socket failed to load: No such file or directory.
2015-11-04T09:00:01.097035+01:00 linux-nfs systemd: pam_unix(systemd-user:session): session opened for user root by (uid=0)
2015-11-04T09:00:01.155633+01:00 linux-nfs CRON[2672]: pam_unix(crond:session): session closed for user root
2015-11-04T09:00:32.158435+01:00 linux-nfs CRON[2671]: pam_unix(crond:session): session closed for user root
2015-11-04T09:00:32.209269+01:00 linux-nfs systemd: pam_unix(systemd-user:session): session closed for user root
2015-11-04T09:03:28.455690+01:00 linux-nfs kernel: [  772.467035] perf interrupt took too long (2515 > 2500), lowering kernel.perf_event_max_sample_rate to 50000
2015-11-04T09:09:06.466366+01:00 linux-nfs sudo:     root : TTY=pts/1 ; PWD=/home/anton/bosto_14wa-master/scripts ; USER=root ; COMMAND=/usr/bin/tail -f /var/log/messages
2015-11-04T09:09:06.467240+01:00 linux-nfs sudo: pam_unix(sudo:session): session opened for user root by anton(uid=0)

**Comment by antonvdh** [comment]
Closed the issue because whatever I try it the shortcut stays is not changeable for me it is middle mouse button for the pencil.

**Comment by aidyw** [comment]
Hi Anton,
I don't have any better way to contact you but I need to ask you a question about my Kingtee 22HD. I assume you do indeed work for or are involved with bosto-tablet.com. Please try and get back to me.
Thanks
Aidan

**Comment by antonvdh** [comment]
Hello Aidon Walton,

I do not work for Bosto but I have connections with a manager from bosto.
I also have purchased a Bosto Kingtee 22U Mini and love it.

Kind Regards,
Anton vd Haterd

https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=oa-2115-v2-b
Virus-free.
www.avast.com
https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=oa-2115-v2-b
<#m_-8007498048015819137_DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2016-05-20 13:43 GMT+02:00 Aidan Walton notifications@github.com:

**Comment by aidyw** [comment]
Hi Anton.
Well, I too made a purchase through them. I wonder can we take this
offline, private email. It's not something that needs to be shared. How can
I get you via direct email?
Aidan

**Comment by antonvdh** [comment]
Hello Aidan,

Ofcourse you may contact me directly :
antonvdh@gmail.com

Greetings
Anton
Op 20 mei 2016 13:57 schreef "Aidan Walton" <notifications@github.com>:

> Hi Anton.
> Well, I too made a purchase through them. I wonder can we take this
> offline, private email. It's not something that needs to be shared. How can
> I get you via direct email?
> Aidan
>
