### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by thanech** [aidyw/bosto-2g-linux-kernel-module#12]
Aidan, 
I followed the instructions, because I am not a coder :), and I got an error on the "clean" command.
I installed the module fine by simply using "make" instead of "make clean && make".
The error message is here:
`~/bosto-2g-linux-kernel-module $ make clean && make
make -C /lib/modules/4.4.0-57-generic/build M=/home/thane/bosto-2g-linux-kernel-module clean
make[1]: Entering directory '/usr/src/linux-headers-4.4.0-57-generic'
make[1]: Leaving directory '/usr/src/linux-headers-4.4.0-57-generic'
rm detach_usbhid
rm: cannot remove 'detach_usbhid': No such file or directory
Makefile:14: recipe for target 'clean' failed
make: *** [clean] Error 1
`
Anyhow, this kept the make command from completing its task. If I can give you any more info that is helpful concerning this, let me know!
Thanks again for all your work on driver development!

[My current system is Linux Mint 18 (Ubuntu 16.04), KDE, 64bit. Kernel 4.4.0-57-generic.]

**Comment by aidyw** [comment]
Hi,
You should try running these commands as root, otherwise I doubt you will
have the correct privileges to add or delete the files involved. So if the
install process did not write them into place, then clean will fail. So in
both cases run as root.
Aidan
