### ISSUE TITLE
driver for other linux distributions

### ISSUE THREAD

**Issue by antonvdh** [aidyw/bosto-2g-linux-kernel-module#2]
How to install on openSUSE 13.2 (x86_64)

linux-nfs:/home/anton/bosto-2g-linux-kernel-module # make  
gcc detach_usbhid.c -I/usr/include/libusb-1.0 -L/lib/-linux-gnu/libusb-1.0.so.0 -lusb-1.0 -o detach_usbhid  
detach_usbhid.c:2:20: fatal error: libusb.h:
# include <libusb.h>

```
                ^
```

compilation terminated.

**Comment by aidyw** [comment]
This looks like a path problem. Do you see the header file in the include path? Its probably different on SUSE?

Also once again this program has the vendor and product id hard coded. It’s easy to change, but wont detach any other device.

**Comment by aidyw** [comment]
I thought I’d run a rough test with the new code. Seems I’ve caught all the aberrations from the stylus now. Seems to work. Good luck with SUSE.
Aidan

**Comment by antonvdh** [comment]
Wow many thanks I gonny try the new code later today.
Op 3 sep. 2015 17:16 schreef "Aidan Walton" notifications@github.com:

> I thought I’d run a rough test with the new code. Seems I’ve caught all
> the aberrations from the stylus now. Seems to work. Good luck with SUSE.
> Aidan
>

**Comment by antonvdh** [comment]
Can you tell me how you did the install on openSUSE !?.

**Comment by antonvdh** [comment]
Driver works fine for opensuse 13.2
