### ISSUE TITLE
Monoprice 22HD

### ISSUE THREAD

**Issue by dreucifer** [aidyw/bosto-2g-linux-kernel-module#7]
I have what appears to be a rebadged Bosto Kingtee 22HD, but it doesn't seem to report the correct coordinates. The touch is confined to the upper left. The scale is off and there appears to be an acceleration factor affecting the pointer.

**Comment by dreucifer** [comment]
I believe I fixed the issue. The max_x and max_y values in the features struct for the 22HD were the same as the smaller 14WA. I believe I have found the correct values and 1:1 absolute tracking works perfectly now.

**Comment by stacksmith** [comment]
I am happy that you found the correct values, **but how about sharing them**?

**Comment by stacksmith** [comment]
``` c
 static const struct hanwang_features features_array[] = {
    { USB_PRODUCT_BOSTO22HD, "Bosto Kingtee 22HD", HANWANG_BOSTO_22HD,
-       PKGLEN_MAX, 0x27de, 0x1cfe, 0x3f, 0x7f, 0x0400 }, // REPLACE THIS LINE WITH NEXT!
+       PKGLEN_MAX, 0xDBE8, 0x79BF, 0x3f, 0x7f, 0x0800 },
...
 };
 };
```

**Comment by aidyw** [comment]
Hey folks,
Why are you changing these values. The hardware reports this is a fixed int
and I have verified that the values are correct for the 22HD and Leslie did
the same for the 14WA. IMHO if you have problems with some specific
software any translations should take place in user-space, not in the
driver.
What is you reason for adjusting those we have already.
Aidan

**Comment by stacksmith** [comment]
@aidyw, firstly, thanks for the driver.  I am open to any suggestions, but this is the only way I got my monoprice to work.

On my monoprice 22" your values resulted in a tiny active rectangle in the upper left of the screen.  
This is not for any specific software (unless you count Ubuntu as specific software).  Perhaps we have a different model?  My monoprice has a IIIP mark on the bottom and back.

Setting the values as listed above matches the entire display perfectly.  I am not sure what I would use in user-space to translate pen coordinates.  I am open to suggestions, as I obviously do not know what I am doing - but the solution listed above works for me.

**Comment by aidyw** [comment]
I just pushed another new development branch, and added some debug options to print the values of ABS_X ABS_Y and ABS_PRESSURE as they are seen directly from the hardware.
Try compiling this and test to see what your tablet reports.

BTW unrelated, but I am having a major headache with pressure, in fact its not working. Well thats not striclty true, it is reported to the kernel and I can see it with the output from 'evtest' but xinput --list --long, shows no change, something has broken on my system.

Could you try this new branch and let me know if you have pressure working.
Thanks

**Comment by aidyw** [comment]
The point being, with respect to x and y values. If you are getting something different from your hardware, we need to add a new device to the driver, not alter the existing devices.

**Comment by stacksmith** [comment]
What do you think is a good way of handling the range discerpancy?  My device gives off the same USB id, 0b57:9016.  Your driver is fine, it's just the range that is different...

I will try compiling your driver and report.

**Comment by stacksmith** [comment]
Also, before I screw up my system, does your make uninstall work?  I'm a-scared that I'll never get my tablet to work again...

**Comment by aidyw** [comment]
Well there are other fields from USB  iManuafacturer & iProduct. check
lsusb -v, but my Bosto shows Error in both cases. Not very helpful, maybe
they are sending chinese characters :)

Anyway, what does yours say

Bus 001 Device 016: ID 0b57:9016 Beijing HanwangTechnology Co., Ltd
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               1.10
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0
  bDeviceProtocol         0
  bMaxPacketSize0        64
  idVendor           0x0b57 Beijing HanwangTechnology Co., Ltd
  idProduct          0x9016
  bcdDevice            1.02
  iManufacturer           1 (error)
  iProduct                2 (error)
  iSerial                 0
  bNumConfigurations      1

**Comment by stacksmith** [comment]
@aidyw, I compiled your kernel and am now getting wrong scaling... What do I need to do to read out debug info?

my lsusb -v:

```
Bus 001 Device 024: ID 0b57:9016 Beijing HanwangTechnology Co., Ltd 
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               1.10
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x0b57 Beijing HanwangTechnology Co., Ltd
  idProduct          0x9016 
  bcdDevice            1.02
  iManufacturer           1 
  iProduct                2 
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           34
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              300mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.10
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     194
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x000a  1x 10 bytes
        bInterval               1
```

**Comment by aidyw** [comment]
I think it works, I dont use it to be honest . I just tried it again on my
system and no problems.

**Comment by aidyw** [comment]
I refer to the uninstall

**Comment by stacksmith** [comment]
OK, too late for that...  How do I get debug?

**Comment by aidyw** [comment]
read README.md

**Comment by stacksmith** [comment]
Yes, tried to tail /var/log/kern.log, getting nothing useful:

```
Nov  3 10:42:59 democles kernel: [109718.862510] vgaarb: this pci device is not a vga device
Nov  3 10:43:29 democles kernel: [109748.862575] vgaarb: this pci device is not a vga device
Nov  3 10:43:34 democles kernel: [109754.075222] pcieport 0000:00:1c.5: AER: Corrected error received: id=00e5
Nov  3 10:43:34 democles kernel: [109754.075230] pcieport 0000:00:1c.5: PCIe Bus Error: severity=Corrected, type=Physical Layer, id=00e5(Receiver ID)
Nov  3 10:43:34 democles kernel: [109754.075234] pcieport 0000:00:1c.5:   device [8086:9d15] error status/mask=00000001/00002000
Nov  3 10:43:34 democles kernel: [109754.075236] pcieport 0000:00:1c.5:    [ 0] Receiver Error        
Nov  3 10:43:59 democles kernel: [109778.862936] vgaarb: this pci device is not a vga device
Nov  3 10:44:29 democles kernel: [109808.862553] vgaarb: this pci device is not a vga device
Nov  3 10:44:59 democles kernel: [109838.862656] vgaarb: this pci device is not a vga device
Nov  3 10:45:29 democles kernel: [109868.862494] vgaarb: this pci device is not a vga device
```

**Comment by stacksmith** [comment]
I am not sure what 'pattern matching' means.  Can you give me an example of what would work for you?

**Comment by aidyw** [comment]
echo in the field you want. 
echo -n 'format "Bosto ABS" +p' > /sys/kernel/debug/dynamic_debug/control

tail -f /var/log/syslog

not kern

**Comment by aidyw** [comment]
what Linux flavour

**Comment by stacksmith** [comment]
I am on Ubuntu 16.04.  sudo echo -n 'format "Bosto ABS" +p' > /sys/kernel/debug/dynamic_debug/control fails: permission denied...

**Comment by aidyw** [comment]
root!

**Comment by stacksmith** [comment]
Sorry, I thought sudo would work.  This is my first foray into kernel; please be patient.

**Comment by aidyw** [comment]
your not alone

**Comment by stacksmith** [comment]
OK, x tops at 27DE, approximately 4 inches away from upper corner.
y tops at 1CFE, about 3 inches down.

**Comment by aidyw** [comment]
well, these are the same values as mine....or

**Comment by aidyw** [comment]
ahh, hang on I limit them in the code

**Comment by stacksmith** [comment]
abs pressure not responsive, at 7FF.  However, I had it working in the GIMP.

**Comment by aidyw** [comment]
```
if (x > bosto_2g->features->max_x) {x = bosto_2g->features->max_x;}
if (y > bosto_2g->features->max_y) {y = bosto_2g->features->max_y;}
```

**Comment by aidyw** [comment]
but you see pressure from the driver

**Comment by stacksmith** [comment]
Nah, always 7FF.

**Comment by stacksmith** [comment]
Should I take the limit code out and try it?

**Comment by aidyw** [comment]
hmmm, me too now. hang on

**Comment by aidyw** [comment]
do what you need to

**Comment by aidyw** [comment]
shit that was my misatke. I hardcoded it.

**Comment by aidyw** [comment]
just a sec. I was testing when I branched. Give me a moment

**Comment by aidyw** [comment]
do you use google hangouts

**Comment by stacksmith** [comment]
Nah, I am ungoogled.  IRC?

**Comment by aidyw** [comment]
okay compile then new code I just pushed

**Comment by aidyw** [comment]
Hmm good old irc. well,

**Comment by stacksmith** [comment]
I just took those limiting lines out...
y-max: 7bb3
x-max dbe8
approx

**Comment by stacksmith** [comment]
No luck with pressure. 7FF

**Comment by aidyw** [comment]
so what irc channel

**Comment by aidyw** [comment]
recompile

**Comment by stacksmith** [comment]
try #bosto on freenode?

**Comment by aidyw** [comment]
up to you, but further up in the code, in the parse logic you will see I hardcoded to 7FF, simpler to pull again of the developemnt branch and then recompile

**Comment by stacksmith** [comment]
OK, recompiled, pressure works really well.

**Comment by aidyw** [comment]
so....once again IRC proves to be a royal pain in the but. When it comes to chat, I never liked it, I never will. I dont want to be a programmer, when I want to communicate.

**Comment by aidyw** [comment]
choose a nicjnmae, have a identify, what you password. Single sign non. Hmmm. I suppose some things just stick where they are and there is no moving forward.

**Comment by stacksmith** [comment]
I agree, not a big fan of IRC.  Just barely figured out how to use thunderbird.  But I hate google tracking my ass even more.

**Comment by aidyw** [comment]
Pressure is working in your apps

**Comment by stacksmith** [comment]
It did before.  I can't really use the pen when it's like this, all over the screen.

**Comment by aidyw** [comment]
I couldnt care less, they can track all day... I have nothing to hide

**Comment by stacksmith** [comment]
Who needs privacy, I did nothing wrong.  You get a different perspective if you grow up in the Soviet Union, for instance.

**Comment by aidyw** [comment]
can you tell me what xinput is doing

You need to work out what X has defined your tablet as, node. So run xinput find the node number then.

xinput --list --long <node>

**Comment by aidyw** [comment]
Yeah sorry for that. But I didnt

**Comment by stacksmith** [comment]
At this rate, you may die in the equivalent of USSR.  Or worse.

**Comment by stacksmith** [comment]
```
⎜   ↳ Bosto Kingtee 22HD                        id=10   [slave  pointer  (2)]
    Reporting 5 classes:
        Class originated from: 10. Type: XIButtonClass
        Buttons supported: 7
        Button labels: "Button Unknown" "Button Unknown" "Button Unknown" "Button Wheel Up" "Button Wheel Down" "Button Horiz Wheel Left" "Button Horiz Wheel Right"
        Button state:
        Class originated from: 10. Type: XIValuatorClass
        Detail for Valuator 0:
          Label: Abs X
          Range: 0.000000 - 10206.000000
          Resolution: 0 units/m
          Mode: absolute
          Current value: 2447.000000
        Class originated from: 10. Type: XIValuatorClass
        Detail for Valuator 1:
          Label: Abs Y
          Range: 0.000000 - 7422.000000
          Resolution: 0 units/m
          Mode: absolute
          Current value: 2561.000000
        Class originated from: 10. Type: XIValuatorClass
        Detail for Valuator 2:
          Label: Abs Pressure
          Range: 0.000000 - 2047.000000
          Resolution: 0 units/m
          Mode: absolute
          Current value: 0.000000
        Class originated from: 10. Type: XIValuatorClass
        Detail for Valuator 3:
          Label: Abs Misc
          Range: 0.000000 - 0.000000
          Resolution: 0 units/m
          Mode: absolute
          Current value: 2.000000
```

**Comment by aidyw** [comment]
so Im on irc

**Comment by stacksmith** [comment]
join #bosto on freenode.  I think it lets you start channels... I hope.  I am stacksmith.

**Comment by aidyw** [comment]
well I see you , but your not saying much

**Comment by aidyw** [comment]
A little further comment on our devices. We seem to have identical tablet, right down to the release version '1.02'. I don't see any other way to separate these and I will be very surprised if the raw data from the tablet is not identical. Please check carefully.

**Comment by dreucifer** [comment]
Yes, my original intention was to add a new device with new limits, but I couldn't find a way to differentiate the two in code.

#### Possible Solutions
1. Add a boolean parameter to the module. Load the driver with 'insmod bosto_2g monoprice=1" and it uses my defaults, otherwise it leaves everything the way it is.
2. Remove the hard limits entirely and leave constraints to userspace tools.
3. Completely fork the drivers.

None of these are very elegant, but such is life, eh?

**Comment by stacksmith** [comment]
Well, while this driver is a testing ground, there are many problems with this driver... I am just forking off as I have no idea why 90% of the driver is written the way it is.

**Comment by aidyw** [comment]
Option 1 seems reasonable. However I am still deeply surprised by what you
are telling me, it is a big surprise that apparently identical devices are
producing different outputs. However having said that we are dependent on
the manufactures actually considering the need to keep each and every
device uniquely coded. I tried extremely hard to get some data from the
iProduct descriptor, in the hope that these strings will separate the two,
this might still be possible, but it is not too reliable, as sometimes I
get valid Chinese characters reported by the string request and other times
the tablet spits back, malformed. Its unpredictable and I think your
suggestion is going to be more reliable to be honest.
